main/views/dates.py
from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect

from main.models import EnableDay, ComeMenber, EnableDay_comment, User, Each_snack
from main.forms import Day_Comment, SnackForm
from .auth import login_required
from main import db

bp = Blueprint('date', __name__, url_prefix='/date')

@bp.route('/')
def date():
    form = Day_Comment()
    year, month, day = request.args.get('dates', "2023-9-18", str).split('-')
    date = year + ',' + month + ',' + day
    # 오는사람 안오는사람 구분하기
    member = ComeMenber.query.filter_by(date=date).first()
    if not member:
        c_p_list, n_c_p_list = [''], ['']
    else:
        c_p_list, n_c_p_list = list((member.comeuser).split(',')), list((member.not_comeuser).split(','))
    # 그날의 내용 보여주기
    contents_list = EnableDay_comment.query.filter_by(date=date)
    name_list = []
    for i in contents_list:
        user = User.query.filter_by(id=i.id_user).first()
        name_list.append(user.username)
    # 그날 파인만 하는지 안하는지 알려주기
    e_d = EnableDay.query.filter_by(year=year, month=month, day = day).first()
    if e_d:
        enable_feynman = True
    else:
        enable_feynman = False
    return render_template('/day/date_detail.html', year = year, month = month, day = day, c_p_list = c_p_list, n_c_p_list = n_c_p_list,
                            form = form, contents_list = contents_list, name = name_list, enable_feynman = enable_feynman)


@bp.route("/EnableDay")
@login_required
def enableDay():
    year, month, day = request.args.get('dates', "2023-9-18", str).split('-')
    e_d = EnableDay.query.filter_by(year=year, month=month, day = day).first()
    days = EnableDay(year=year, month=month, day = day)
    if e_d:
        db.session.delete(e_d)
    else:
        db.session.add(days)
    db.session.commit()
    return redirect(url_for('main.index'))


@bp.route('/Record')
@login_required
def record():
    year, month, day = request.args.get('dates', "2023-9-18", str).split('-')
    come_notcome = request.args.get('come', "T", str)
    date = year + ',' + month + ',' + day
    come_people = ComeMenber.query.filter_by(date=date).first()
    if not come_people:
        # 데이터베이스에 날짜가 없을 때
        if come_notcome == 'T':    
            today_people = ComeMenber(date = date, comeuser = ','+g.user.name, not_comeuser = "")
        else:
            today_people = ComeMenber(date = date, comeuser = "", not_comeuser = ','+g.user.name)
        db.session.add(today_people)
        db.session.commit()
        return redirect( url_for('date.date')+"?dates=%s-%s-%s" %(year, month, day) )

    else:
        # 데이터베이스에 날짜가 있을 때
        c_p_list, n_c_p_list = list((come_people.comeuser).split(',')), list((come_people.not_comeuser).split(','))

        #이름이 포함되있을 경우
        if g.user.name in c_p_list:
            #온다에 들어있을 때
            c_p_list.remove(g.user.name)
        elif g.user.name in n_c_p_list:
            #오지 않는다에 들어있을 때
            n_c_p_list.remove(g.user.name)
        
        #이름이 아무곳에도 포함 안되있을 경우
        if come_notcome == 'T':    
            c_p_list.append(g.user.name)
        else:
            n_c_p_list.append(g.user.name)

        c_p_input, c_n_p_input = ",".join(c_p_list), ",".join(n_c_p_list)
        all_input = ComeMenber(date = date, comeuser = c_p_input, not_comeuser = c_n_p_input)
        db.session.delete(come_people)
        db.session.commit()
        db.session.add(all_input)
        db.session.commit()
        return redirect( url_for('date.date')+"?dates=%s-%s-%s" %(year, month, day) )


@bp.route('/Comment/<string:year>/<string:month>/<string:day>', methods = ("GET","POST"))
@login_required
def comment(year, month, day):
    date_list = [year, month, day]
    date_input = ','.join(date_list)
    form = Day_Comment()
    if request.method == 'POST' and form.validate_on_submit():    
        user = User.query.filter_by(username=g.user.username).first()
        text = EnableDay_comment(a_user = user, Title = form.Title.data , content = form.content.data, date = date_input)
        db.session.add(text)
        db.session.commit()
    elif (not form.Title.data) and (not form.content.data):    
        flash("제목과 내용은 반드시 기입해야 합니다.")
    elif not form.Title.data:
        flash("제목은 반드시 기입해야 합니다.")
    elif not form.content.data:
        flash("내용은 반드시 기입해야 합니다.")
    return redirect( url_for('date.date')+"?dates=%s-%s-%s" %(year, month, day) )


@bp.route('/Snack', methods = ("GET","POST"))
@login_required
def snack():
    year, month, day = request.args.get('dates', "2023-9-18", str).split('-')
    date = year + ',' + month + ',' + day
    come_people = ComeMenber.query.filter_by(date=date).first()
    if come_people:
        if (come_people.comeuser != ""):
            come_people_name_list = list(come_people.comeuser.split(','))
            come_people_name_list.remove('')
            # 이름을 아이디로 바꾸기
            sub1 = []
            for name in come_people_name_list:
                each_user = User.query.filter_by(name=name).first()
                sub1.append(each_user.username)
                come_people_name_list = sub1
            #이름을 아이디로 바꾸기 끝
        else:
            come_people_name_list = False
    else:
        come_people_name_list = False
    
    form = SnackForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=g.user.username).first()
        text = Each_snack(date = date, content = form.snack_content.data, a_user = user)
        db.session.add(text)
        db.session.commit()
    
    snack_all_data = Each_snack.query.filter_by(date=date)
    return render_template('/day/snack.html', come_people_name_list = come_people_name_list,  form = form, snack_all_data = snack_all_data, 
                           year = year, month = month, day = day)


@bp.route('/Delete_snack/<int:snack_id>', methods = ("GET","POST"))
@login_required
def delete_snack_function(snack_id):
    year, month, day = request.args.get('dates', "2023-9-18", str).split('-')
    delete_snack = Each_snack.query.filter_by(id=snack_id).first()
    db.session.delete(delete_snack)
    db.session.commit()
    return redirect( url_for('date.snack')+"?dates=%s-%s-%s" %(year, month, day) )


@bp.route('/Delete_comment/<int:comment_id>', methods = ("GET","POST"))
@login_required
def delete_comment_function(comment_id):
    year, month, day = request.args.get('dates', "2023-9-18", str).split('-')
    delete_comment = EnableDay_comment.query.filter_by(id=comment_id).first()
    db.session.delete(delete_comment)
    db.session.commit()
    return redirect( url_for('date.date')+"?dates=%s-%s-%s" %(year, month, day) )

main/views/day.py
from flask import Blueprint, render_template, request
from datetime import datetime
from werkzeug.utils import redirect

from main.models import EnableDay

bp = Blueprint('day', __name__, url_prefix='/day')


# 달력 화면 코드
@bp.route('/')
def day():
    year = request.args.get('year', datetime.now().year, int)
    month = request.args.get('month', datetime.now().month, int)
    today_list = [datetime.now().year, datetime.now().month, datetime.now().day]
    e_d = EnableDay.query.order_by()
    if request.args.get('dates', '', str) != '':
        give_str = request.args.get('dates', "기본값 입력", str)
        return redirect('/date?dates=%s' %give_str)
    else:
        return render_template('/day/test2.html', year = year, month = month, t_list=today_list, e_d = e_d)


# 이거 test2에 꺼녛을 방법 생각해봐
'''
        {% for i in e_d %}
        {% elif (i.year == year) and (i.month == month) and (i.day == (a|int)) %}
            <td onClick="location.href='/date?dates={{year}}-{{month}}-{{a}}'" class="blinking table-danger"> <!-- class="table-danger table-active"-->
                {{a | safe}}
            </td>
        {% endfor %}
'''

main/templates/day/date_detail.html
{% extends "main.html" %}

{% block using_flask %}
{%with messages = get_flashed_messages()%}
{%if messages %}
    <script type="text/javascript">
        alert("{{messages[-1]}}");
    </script>
{%endif%}
{%endwith%}
{% endblock using_flask %}


{% block first_body %}
<h1 class="text-center my-3 mb-3">
    {{year}}년 {{month}}월 {{day}}일
</h1>
<div class="container border-top">
    <a href="{{ url_for('date.enableDay')+'?dates'+'=%s-%s-%s' %(year, month, day) }}"><button type="button" class="btn btn-info my-3">
        파인만 하는날!!!</button></a>
    {% if enable_feynman %}
    <br>
    <br>
    <div class="border-bottom">
        <a href="{{ url_for('date.record')+'?dates'+'=%s-%s-%s' %(year, month, day)+'&come=T' }}"><button type="button" class="btn btn-success my-2 mx-2">갈 수 있다</button></a>
        {% for people in c_p_list %}
        {{people}}
        {% endfor %}
    </div>
    <br>
    <div class="border-bottom">
        <a href="{{ url_for('date.record')+'?dates'+'=%s-%s-%s' %(year, month, day)+'&come=F' }}"><button type="button" class="btn btn-danger my-2 mx-2">못간다</button></a>
        {% for people in n_c_p_list %}
        {{people}}
        {% endfor %}
    </div>
    <br>
    <a href="{{ url_for('date.snack')+'?dates'+'=%s-%s-%s' %(year, month, day) }}"><div class="card mb-3">
        <img src="..\..\static\image\cooki3-1.jpg" class="card-img-top" alt="cookie">
        <div class="card-body">
            <h5 class="card-title">따봉과자</h5>
            <p class="card-text">오늘 파인만을 나온다면 먹고싶은 과자를 3천원 이내로 말해 주십시오.</p>
        </div>
    </div></a>
    {% endif %}
    
    <br>
    {% if year=='2023' and month=='9' and day=='18' %}
        <h4>오늘은 그가 군대를 가는 날입니다. 부디 추보를 해주시기 바랍니다.</h4>
    {% endif %}
    <br>

    {% for content in contents_list %}
    <div class="card mb-3"> 
        <div class="card-header">
            <h5 class="card-title mt-2">{{ content.Title }}</h5>
        </div>
        <div class="card-body">
            <p class="card-text">{{ content.content }}</p>
            <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
            {% if (content.id_user == g.user.id) or (g.user.name == "김민경") or (g.user.name == "양승빈") %}
            <a href="{{ url_for('date.delete_comment_function', comment_id = content.id)+'?dates'+'=%s-%s-%s' %(year, month, day) }}"  
            class="btn btn-sm btn-outline-secondary">삭제</a>
            {% endif %}
            <div class="d-flex justify-content-end">
                <div class="badge badge-light text-muted">
                    <font size=3>-{{ name[loop.index0] }}-</font>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

    <br>      
    <h3>내용 입력하기</h3>
    <div class="border-bottom mb-2"></div>
    <div class="card">
        <form action="{{ url_for('date.comment', year=year, month=month, day=day) }}" method="post">
            {{ form.csrf_token }}
            <div class="card-header">
                <label for="Title" class="form-label mt-2"><h5>제목</h5></label>
                <input {% if not g.user %}disabled{% endif %}
                    type="text" id="Title" name="Title" class="form-control mb-2" aria-describedby="passwordHelpBlock">
                {% if get_flashed_messages() %}
                <div id="passwordHelpBlock" class="form-text text-danger">
                    제목을 기입하여 주세요.
                </div>
                {% endif %}
            </div>
            <div class="card-body">
                <label for="content" class="form-label"><h5 class="card-title">내용</h5></label>
                <textarea {% if not g.user %}disabled{% endif %}
                    name="content" id ="content" class="form-control mb-2" rows="10"></textarea>
                {% if get_flashed_messages() %}
                <div id="passwordHelpBlock" class="form-text text-danger my-2">
                    내용을 기입하여 주세요.
                </div>
                {% endif %}
                <button type="submit" class="btn btn-primary">내용등록</button>
            </div>
        </form>
    </div>

</div>
<h5>&nbsp;</h5>


{% endblock first_body %}

main/templates/day/snack.html
{% extends "main.html" %}
{% block first_body %}

{% if come_people_name_list != False %}
<div class=" container row row-cols-1 row-cols-md-3 g-4 my-3 mx-1">
    {% for name in come_people_name_list %}
    <div class="col">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title mt-2">{{name}}</h5>
            </div>
            <div class="card-body">
                <P>오늘의 과자:</P>
                {% if (not g.user) or (name != g.user.username) %}
                <ul>
                    {% for each_data in snack_all_data %}
                        {% if each_data.username_user == name %}  
                        <li>
                            {{each_data.content}}                           
                        </li>
                        <br>
                        {% endif %}
                    {% endfor %}
                </ul>
                <textarea disabled name="snack_content" id ="snack_content" class="form-control mb-2"></textarea>
                {% else %}
                {% include "form_errors.html" %}
                <form method="post">
                    <ul>
                        {% for each_data in snack_all_data %}
                            {% if each_data.username_user == name %}
                            <li>
                                <div style="float:left;">
                                {{each_data.content}}
                                </div>
                                <div style="float:right;">
                                    <a href="{{ url_for('date.delete_snack_function', snack_id = each_data.id)+'?dates'+'=%s-%s-%s' %(year, month, day) }}" 
                                    class="btn btn-sm btn-outline-secondary">삭제</a>
                                </div>
                            </li>
                            <br>
                            {% endif %}
                        {% endfor %}
                    </ul>
                    {{ form.csrf_token }}
                    <textarea name="snack_content" id ="snack_content" class="form-control mb-2"></textarea>
                    <button type="submit" class="btn btn-primary">내용등록</button>
                </form>
                {% endif %} 
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% else %}
<div class="container mt-3">
    <h3>오늘은 아무도 파인만을 오지 않습니다 :( </h3>
    <h5>너무하네요....</h5>
    <a href="{{ url_for('main.index') }}"><button type="button" class="btn btn-info">돌아가기</button></a>
</div>
{% endif %}

{% endblock first_body %}




<!--
    개행없이 한줄에 왼쪽 오른쪽으로 넣을려고 노력한 흔적
<div style="text-align:right">
    <a href="#" class="btn btn-sm btn-outline-secondary">삭제</a>
</div>

<span style="width:49%;">
{{each_data.content}}
</span>
<span style="float:right;width:49%;">
    <a href="#" class="btn btn-sm btn-outline-secondary">삭제</a>
</span>
-->

main/templates/day/test2.html
{% extends "main.html" %}
{% from 'sub.html' import leftarrow, rightarrow %}

{% block first_body %}

{% macro col(dt) %}
<div class="text-center my-3">
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            {% for i in '일월화수목금토' %}
                <th>{{i}}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
    {% for row in range(dt | sdt, dt | edt) | batch(7, '&nbsp;') %}
        <tr> 
        {% for a in row %}
        {% if ((a|int) ==t_list[2]) and (year == t_list[0]) and (month == t_list[1]) %}
            <td onClick="location.href='/date?dates={{year}}-{{month}}-{{a}}'" class="blinking table-primary"> <!-- class="table-danger table-active"-->
                {{a | safe}}
            </td>
        {% elif year |check(month, a, e_d) %}
            <td onClick="location.href='/date?dates={{year}}-{{month}}-{{a}}'" class="blinking table-danger"> <!-- class="table-danger table-active"-->
                {{a | safe}}
            </td>
        {% elif ( (a|int) <= 0) %}
            <td>
                &nbsp;
            </td>
            {% else %}
            <td onClick="location.href='/date?dates={{year}}-{{month}}-{{a}}'" class="blinking"> <!-- class="table-danger table-active"-->
                {{a | safe}}
            </td>
        {% endif %}
        {% endfor %}
        </tr>
    {% endfor %}
    </tbody>
</table>
</div>
{% endmacro %}

<div class="container">
    <div class="my-3">
        <div>
            <h2 class="text-center text-primary">
                <small><a href="/day?year={{year - 1}}&month={{month}}" class="text-muted">{{year - 1}}</a></small>

                {{leftarrow()}}
                {{year}}년
                {{rightarrow()}}
                
                <small><a href="/day?year={{year + 1}}&month={{month}}" class="text-muted">{{year + 1}}</a></small>
            </h2>
            
            <h1 class="text-center text-primary"> <!--text-primary-->
                {% if month - 1 == 0 %}
                <small><a href="/day?year={{year - 1}}&month=12" class="text-muted">12</a></small>
                {% else %}
                <small><a href="/day?year={{year}}&month={{month - 1}}" class="text-muted">{{month - 1}}</a></small>
                {% endif %}

                {{leftarrow('mx-1')}}
                {{month}}월
                {{rightarrow('mx-1')}}

                {% if month + 1 == 13 %}
                <small><a href="/day?year={{year + 1}}&month=1" class="text-muted">1</a></small>
                {% else %}
                <small><a href="/day?year={{year}}&month={{month + 1}}" class="text-muted">{{month + 1}}</a></small>
                {% endif %}
            </h1>
        </div>
        <div class="border-bottom"></div>
    {% set dt = '%s-%s-01' %(year, month) %}
    {{col(dt)}}
    </div>
    <div>
        <form href="/date">
            <input type="date" name="dates" class="form-control my-2">
            <input class="btn btn-primary" type="submit" value="Submit">
        </form>
    </div>

    <button type="button" onClick="location.href='/day?year={{t_list[0]}}&month={{t_list[1]}}'" class="btn btn-secondary my-3">오늘 날짜</button>
    {% if g.user %}
        {% if (g.user.name == "오준원") or (g.user.name == "오자우") %}
        <h5>안녕하세요 오징어님!</h5>    
        {% else %}
        <h5>안녕하세요 {{ g.user.name }}님!</h5>    
        {% endif %}
    {% endif %}
    <h5>오늘의 날짜는 {{t_list[0]}}년 {{t_list[1]}}월 {{t_list[2]}}일 입니다.</h5>
</div>



{% endblock first_body %}