main/views/auth.py
from flask import Blueprint, render_template, request, url_for, flash, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect
import functools

from main import db
from main.forms import UserCreateForm, UserLoginForm
from main.models import User

bp = Blueprint("auth",__name__, url_prefix='/auth')


@bp.route("/signup/", methods = ("GET","POST"))
def signup():
    form = UserCreateForm()
    if request.method == "POST" and form.validate_on_submit():
        user1 = User.query.filter_by(username=form.nickname.data).first()
        user2 = User.query.filter_by(username=form.name.data).first()
        if (not user1) and (not user2):
            user = User(name = form.name.data, username = form.nickname.data, password = generate_password_hash(form.password1.data))
            db.session.add(user)
            db.session.commit()
            session.clear()
            session["user_id"] = user.id
            return redirect(url_for("main.index"))
        else:
            flash("중복된 사용자입니다.")
    return render_template("/auth/signup.html", form = form)

@bp.route("/login/", methods=("POST","GET"))
def login():
    form = UserLoginForm()
    if request.method == "POST" and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username=form.nickname.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        if error == None:
            session.clear()
            session["user_id"] = user.id
            return redirect(url_for("main.index"))
        flash(error)
    return render_template("auth/login.html", form=form)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))



def login_required(view):
    @functools.wraps(view)
    def wrapped_view(*args, **kwargs):
        if g.user is None:
            flash("위 기능은 로그인 이후에 가능합니다.")
            return redirect(url_for('auth.login'))
        return view(*args, **kwargs)
    return wrapped_view



@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)

main/views/main_views.py
from flask import Blueprint, url_for
from werkzeug.utils import redirect

bp = Blueprint("main",__name__, url_prefix='/')

@bp.route('/')
def index():
    return redirect(url_for('day.day'))

main/views/notice.py
from flask import Blueprint, render_template

bp = Blueprint('notice', __name__, url_prefix='/notice')

@bp.route("/")
def notice_main():

    return render_template("/notice/notice.html")

main/templates/form_errors.html
<!--필드오류-->
{% for field, errors in form.errors.items() %}
<div class="alert alert-danger" role="alert">
    <strong>{{form[field].label}}</strong>: {{','.join(errors) }}
</div>
{% endfor %}


<!--flash 오류-->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

main/templates/main.html
{% block using_flask %}
{% endblock %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>feynman_ssu site</title>
        
        <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">

        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    </head>

    <body>
        {% include "navbar.html" %}

        {% block first_body %}
        {% endblock %}

        <!-- jquery 시작 -->
        <script src="{{ url_for('static', filename='jquery-3.7.0.min.js') }}"></script>
        <!-- jquery 끝 -->

        <!-- bootstrap 시작 -->
        <script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
        <!-- jquery 끝 -->

    </body>
</html>

main/templates/navbar.html
<!--네비게이션 바 시작-->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="/day"><font size=5>Feynman</font></a>     <!--네비게이션 로고-->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>      <!--햄버거모양-->
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                {% if g.user %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">{{ g.user.username }} (로그아웃)</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">로그인</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signup') }}">회원가입</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('notice.notice_main') }}">공지사항</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://www.feynmanlectures.caltech.edu/">Lecture</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!--네비게이션 바 끝-->

main/templates/sub.html
{%- macro input(type='text', id='nas', name='nass', value='haha', class='') -%}
<input type="{{type}}" id="{{id}}" name="{{name}}" value="{{value}}" class="container form-control {{class}}">
{%- endmacro -%}

{%- macro textarea(id='nas', name='nass', value='기본값', class='') -%}
<textarea id="{{id}}" name="{{name}}" rows="5" class="form-control {{class}}">{{value}}</textarea>
{%- endmacro -%}

{%- macro radio(text, name='', id='', value='') -%}
<div class="my-1">
    <label for="{{id}}"><input class="form-chack-input" type="radio" name="{{name}}" id="{{id}}" value="{{value}}" > {{text}} </label>
</div>
{%- endmacro -%}


{%- macro leftarrow(class='') -%}
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left {{class}}" viewBox="0 0 16 16">
    <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
</svg>
{%- endmacro -%}

{%- macro rightarrow(class='') -%}
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right {{class}}" viewBox="0 0 16 16">
    <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"/>
</svg>
{%- endmacro -%}

main/templates/test1.html
{% extends "main.html" %}
{% from "sub.html" import input, textarea, radio %}

{% block first_body %}
<div class="container">
    <input type="text" id="userid" name="username" value="111" class="form-control my-3">
    <form href="/day">
        <input type="date" name="dates">
        <p><input type="submit" value="Submit"></p>
    </form>
    <br>
    {{input('password')}}
    <br>
    <br>
    <br>
    <textarea id="" name="" rows="5" class="form-control"></textarea>
    <br>
    {{textarea()}}
    <br>
    <br>
    <div class="form-chack">
        {{radio('1번', 'ha', 'id1')}}
        {{radio('2번', 'ha', 'id2')}}
        {{radio('3번', 'ha', 'id3')}}
    </div>

    <label>파일을 입력하세요 <input type="file"></label>

{% endblock first_body %}